# Let's play with some statistics

### Mean

Mean = Sum of all observations / Total number of observations

In [1]:
import numpy as np

arr = np.array ([1,3,5,7,9])

arr

array([1, 3, 5, 7, 9])

<b> First let do it hardcode

In [2]:
mean = sum(arr)/len(arr)
print (mean)

5.0


<b>With numpy

In [3]:
np.mean(arr)

5.0

Let's assue that we want <b>weighted average</b> that means multiplying some values with elements of array

like 1x1 + 3x2 + 5x3 + 7x4 + 9x5 and then want to find its MEAN

In [4]:
w = np.array([1,2,3,4,5])

np.average(arr, weights = w)

6.333333333333333

<b> Let's talk about 2D array

In [5]:
arr1 = np.array([[1,3,5,7] , [2,4,6,8]])

In [6]:
np.mean (arr1)

4.5

In [7]:
arr1

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

<b>We can even find mean row or column wise using axis

In [8]:
np.mean (arr1, axis = 1)

array([4., 5.])

In [9]:
np.mean (arr1, axis = 0)

array([1.5, 3.5, 5.5, 7.5])

### Median

If total number of elements/2 = 1, then formula will be <b>(n+1)/2</b> and <b>answer will be the seial number of element</b> that is meadian

If total number of elements/2 = 1, then formula will be <b>(n/2th value) + (n/2+1th value)/2</b> and <b>answer will be the 
value it self</b> as median

In [10]:
arr1

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [11]:
arr

array([1, 3, 5, 7, 9])

In [12]:
np.median(arr)

5.0

In [13]:
np.median(arr1)

4.5

### Mode

Mode is nothing but <b>maximum occurance</b> of an element in array

In [14]:
arr2 = np.array([1,3,4,3,2,7,7,9,9,3,4])

In [15]:
arr2

array([1, 3, 4, 3, 2, 7, 7, 9, 9, 3, 4])

There is <b>no specific library</b> available like np.mode but we can use <b>counter module of collections library

In [16]:
from collections import Counter

In [17]:
count = Counter(arr2)

In [18]:
count

Counter({1: 1, 3: 3, 4: 2, 2: 1, 7: 2, 9: 2})

In [19]:
#To find maximum occurance of a number, Counter.most_common(Number of elements we want to find for max)

count.most_common(1)

[(3, 3)]

In [20]:
count.most_common(2)

[(3, 3), (4, 2)]

### Standard Deviation

It is the <b>spread of the data</b> from the mean line or the <b>distance of a point</b> from the mean line

Formula for Standard Deviation is sqrt{ Sigma [ (Xi-X) ] ^2 / N} <br>
Here, <br>
Xi = Element / Number / Data <br>
X = Mean <br>
N = Total Number of elements

In [21]:
marks = np.array([7,3,5,9,1])

Now let's find S.D. with proper formula

In [22]:
def Standard_dev (arr):
    mean = arr.mean()
    final_var = 0
    for i in arr:
        val = (i - mean)**2
        final_var += val
    return (final_var/len(arr))**0.5

We multiplied it with 0.5 because the S.D. comes under roots which means its power is 1/2 = 0.5

In [23]:
Standard_dev (marks)

2.8284271247461903